meta_product_name: "My portfolio"
meta_title: "My portfolio - Félix TIMMEL"
meta_description: "Hi, I'm a junior developer. See my projects here and discover more about me !"
twitter_account: "@product_twitter_account"   # required for Twitter Cards
